# https://docs.travis-ci.com/user/reference/bionic/
dist: bionic

language: generic

services:
  - docker

addons:
  # https://docs.travis-ci.com/user/installing-dependencies/
  apt:
    packages:
      # - wget
      - make
      # - debhelper
      # - git-buildpackage
      # - binutils-arm-linux-gnueabihf

before_install:
  - make dockers/jehon-docker-build.dockerbuild

script:
  - make all-test
  - make all-build

deploy:
  provider: pages # See https://docs.travis-ci.com/user/deployment/pages/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # From https://github.com/settings/tokens, scope "public_repo"
  keep_history: true
  on:
    branch: master
