# https://docs.travis-ci.com/user/reference/bionic/
dist: bionic

language: generic

services:
  - docker

addons:
  # https://docs.travis-ci.com/user/installing-dependencies/
  apt:
    packages:
      # - wget
      - make
      # - debhelper
      # - git-buildpackage
      # - binutils-arm-linux-gnueabihf

before_install:
  - make dockers/jehon-docker-build.dockerbuild

script:
  - make all-test
  - make-in-docker with-docker
