# https://docs.travis-ci.com/user/reference/bionic/
os: linux
dist: bionic

language: generic

services:
  - docker

addons:
  # https://docs.travis-ci.com/user/installing-dependencies/
  apt:
    packages:
      - make

before_install:
  - make dockers/jehon-docker-build.dockerbuild

script:
  - make all-test
  - make all-build

deploy:
  # See https://docs.travis-ci.com/user/deployment/pages/
  provider: pages
  skip_cleanup: true
  # cleanup: false
  token: $GITHUB_TOKEN  # From https://github.com/settings/tokens, scope "public_repo"
  keep_history: true
  local_dir: repo/
  on:
    branch: master
