#!/usr/bin/env bash

# This script can be run more than once

set -o errexit

if [[ "$(whoami)" != "root" ]]; then
    echo "You need to be root to run this script"
    exit 255
fi

HOSTNAME="$1"
JH_DEFAULT_PWD="$2"

export DEBIAN_FRONTEND=noninteractive
export JH_PKG_MINIMAL_NAME="jehon"

if [ -r repo/"${JH_PKG_MINIMAL_NAME}.deb" ]; then
    LOCAL_DEB="repo/${JH_PKG_MINIMAL_NAME}.deb"
    echo "*** Using local deb: $LOCAL_DEB"
fi

if [ -n "$JH_LOCAL_STORE" ]; then
    LOCAL_DEB="$JH_LOCAL_STORE/${JH_PKG_MINIMAL_NAME}.deb"
    echo "*** Using local store: $LOCAL_DEB"
fi

if [ ! -r "$LOCAL_DEB" ]; then
    echo "*** Installing source from github"
    LOCAL_DEB="/tmp/${JH_PKG_MINIMAL_NAME}.deb"
    wget "http://jehon.github.io/packages/${JH_PKG_MINIMAL_NAME}.deb" -O "$LOCAL_DEB"
fi

echo "*** Using deb: $LOCAL_DEB"

apt-get --yes update
apt-get install --yes "$LOCAL_DEB"

# shellcheck source=/dev/null
. jh-lib

apt-get --yes update
apt-get --yes upgrade

if [ -n "$HOSTNAME" ]; then
    header_start "Setting the hostname to $HOSTNAME"
    # shellcheck disable=SC2029
    hostnamectl set-hostname "$HOSTNAME"
    header_done
fi

if [ -n "$JH_DEFAULT_PWD" ]; then
    header_start "Setup password for user jehon"
    echo "jehon:$JH_DEFAULT_PWD" | passwd jehon
    printf "%s\n%s\n" "$JH_DEFAULT_PWD" "$JH_DEFAULT_PWD" | smbpasswd -s -a jehon
    header_done
fi

if ! jh-in-docker && ! jh-in-wsl; then
    echo "*** Enabling firewall"
    # Wait for xtable lock to be available
    iptables -L -n --wait >/dev/null
    ufw --force enable
fi

if [ -n "$(virt-what)" ]; then
    echo "*** Disable gui on startup $(virt-what)"
    echo " could be reenabled with systemctl set-default graphical"
    systemctl set-default multi-user.target
fi

#
# Now we have our traditional setup
#
#

# shellcheck source=/dev/null
. jh-lib

/usr/sbin/jh-backup-boot

cat <<EOD

*** Install done ***
SSH is enabled through the firewall

You may now install:

    - delete this scrip:                          rm -f "$0"
    - install packages:                           sudo apt install jehon-packages jehon-desktop
    - setup hyperv:                               sudo jh-setup-hyperv
    - download the git repositories:              sudo jh-dev-setup
    - install snaps:                              sudo apt jh-snap-install

You also need to logout/login to jump into docker group before testing repositories

EOD
