#!/usr/bin/env bash

# This script can be run more than once

set -o errexit

if [[ "$(whoami)" != "root" ]]; then
    echo "You need to be root to run this script"
    exit 255
fi

export DEBIAN_FRONTEND=noninteractive
export JH_PKG_MINIMAL_NAME="jehon"

if [ -r repo/"${JH_PKG_MINIMAL_NAME}.deb" ]; then
    LOCAL_DEB="repo/${JH_PKG_MINIMAL_NAME}.deb"
    echo "*** Using local deb: $LOCAL_DEB"
fi

if [ -n "$JH_LOCAL_STORE" ]; then
    LOCAL_DEB="$JH_LOCAL_STORE/${JH_PKG_MINIMAL_NAME}.deb"
    echo "*** Using local store: $LOCAL_DEB"
fi

if [ ! -r "$LOCAL_DEB" ]; then
    echo "*** Installing source from github"
    LOCAL_DEB="/tmp/${JH_PKG_MINIMAL_NAME}.deb"
    wget "http://jehon.github.io/packages/${JH_PKG_MINIMAL_NAME}.deb" -O "$LOCAL_DEB"
fi

echo "*** Using deb: $LOCAL_DEB"

apt-get install --yes "$LOCAL_DEB"
/usr/bin/jh-apt-configure-repositories

apt-get --yes update
apt-get --yes upgrade

cat <<EOD

*** Install done ***
SSH is enabled through the firewall

You may now install:

    - delete this scrip:                          rm -f "$0"
    - install packages:                           sudo apt install jehon-packages jehon-desktop
    - setup hyperv:                               sudo jh-setup-hyperv
    - download the git repositories:              sudo jh-dev-setup
    - install snaps:                              sudo apt jh-snap-install

You also need to logout/login to jump into docker group before testing repositories

EOD
