#!/usr/bin/env bash

# Create user jehon if it does not exists
if ! id -u jehon >/dev/null 2>&1; then
    U1000GRPS=$(id -Gn 1000 | sed -e 's/ /,/g')

    useradd --groups "$U1000GRPS" --create-home jehon || true

    if [ -x /bin/bash ]; then
        usermod -s /bin/bash jehon
    fi
fi

if ! getent group "docker" >/dev/null; then
    groupadd "docker"
fi

if ! getent group "fuse" >/dev/null; then
    groupadd "fuse"
fi

usermod -a -G "sudo" "jehon" || true
usermod -a -G "docker" "jehon" || true
usermod -a -G "fuse" "jehon" || true

# Fix ssh rights
if [ -r /home/jehon/.ssh ]; then
    chown jehon.jehon -R /home/jehon/.ssh
    chmod go-w -R /home/jehon/.ssh
    if [ -r /home/jehon/.ssh/id_rsa ]; then
        chmod 400 /home/jehon/.ssh/id_rsa
    fi
    if [ -r /home/jehon/.ssh/id_rsa.pub ]; then
        chmod 400 /home/jehon/.ssh/id_rsa.pub
    fi
fi
